# Generated by Django 5.0.2 on 2024-02-25 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('a', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('b', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
                ('k', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('p', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('python_code', models.TextField()),
                ('case', models.CharField(blank=True, max_length=255, null=True)),
                ('time_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('complexity_analysis', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
