# docker-compose.yml

networks:
  default:
    name: sam-network
    external: false

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - dynamodb-local
    environment:
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=fakeMyKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      args:
        MDB_PRO_KEY: ${MDB_PRO_KEY}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - default

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8001:8000"
    networks:
      - default

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - dynamodb-local
    environment:
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=fakeMyKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - TESTING=1
    volumes:
      - ./backend:/app/backend
    networks:
      - default

