# docker-compose-prod.yml
version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_DEBUG=True
    command: gunicorn core.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
