# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # ------------------------------------------------
  # 1) Backend Tests
  # ------------------------------------------------
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build backend test image
        run: |
          docker compose -f docker-compose.yml build test

      - name: Run backend tests
        run: |
          docker compose -f docker-compose.yml run --rm test /bin/bash -c "
            python backend/scripts/init_db.py || true
            pytest --cov=backend --cov-report=term-missing --cov-report=html:coverage/html backend/tests
          "

  # ------------------------------------------------
  # 2) Frontend Tests
  # ------------------------------------------------
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # native libs for canvas
      - name: Install canvas build libs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            build-essential libcairo2-dev libpango1.0-dev libjpeg-dev \
            libgif-dev librsvg2-dev pkg-config

      # inject key → install → scrub key (always)
      - name: Install deps (with key management)
        working-directory: frontend
        env:
          MDB_PRO_KEY: ${{ secrets.MDB_PRO_KEY }}
        shell: bash
        run: |
          # quick sanity check (prints *** if set, empty otherwise)
          if [ -z "$MDB_PRO_KEY" ]; then
            echo "::error::MDB_PRO_KEY is empty – check repo secrets"; exit 1; fi
          echo "Token length: ${#MDB_PRO_KEY} (masked)"
          set -e
          node scripts/addKey.cjs
          npm ci --prefer-offline --no-audit
          node scripts/removeKey.cjs

      - name: Run Vitest suite
        working-directory: frontend
        run: npm test -- --run

